/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-container": "#7c839b",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#0b1c30",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "primary-container": "#131b2e",
        "on-tertiary-fixed": "#0b1c30",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-container": "#75859d",
        "surface-container": "#eceef0",
        "outline-variant": "#c6c6cd",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb",
        "primary-fixed": "#dae2fd",
        "outline": "#76777d",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#d8e2ff",
        "inverse-primary": "#bec6e0",
        "primary": "#000000",
        "on-primary-fixed": "#131b2e",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#d3e4fe",
        "surface-tint": "#565e74",
        "on-background": "#191c1e",
        "secondary": "#0058be",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#004395",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001a42",
        "on-surface-variant": "#45464d",
        "tertiary-fixed-dim": "#b7c8e1",
        "secondary-fixed-dim": "#adc6ff",
        "surface": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "tertiary": "#000000",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#2170e4",
        "on-secondary-container": "#fefcff",
        "error": "#ba1a1a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "sidebar-width": "240px",
        "row-height-md": "44px",
        "row-height-sm": "32px",
        "container-padding": "24px",
        "element-gap": "12px",
        "base": "4px"
      },
      "fontFamily": {
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "display": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "mono-sm": ["jetbrainsMono"],
        "label-md": ["Inter"]
      },
      "fontSize": {
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "mono-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
